apiVersion: v1
kind: Pod
metadata:
  name: candy-service-pod
spec:
  securityContext:
    fsGroup: 2000
  serviceAccountName: candy-svc
  containers:
    - name: candy-service-pod
      image: linuxacademycontent/candy-service:1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
      volumeMounts:
        - name: candy-service-config-volume
          mountPath: /etc/candy-service/candy.cfg
  volumes:
    - name: candy-service-config-volume
      configMap:
        name: candy-service-config